#!/bin/bash
# Phase 2 Exploration Script — Protocol & Market Behavior Probing
# 
# This script guides you through understanding the TRV exchange protocol
# in a hands-on way. Use these commands to explore and document findings.
#
# Prerequisites:
#   - Docker + Docker Compose installed
#   - NATS CLI installed: https://github.com/nats-io/natscli
#   - Exchange running: ./run.sh --sim
#   - Run this from the candidate/ directory

set -e

NATS_URL="${NATS_URL:-nats://localhost:4222}"
FEED="AAH6"
SENDER="PYTKR001"

echo "=========================================="
echo "Phase 2: Exchange Protocol Exploration"
echo "=========================================="
echo "NATS URL: $NATS_URL"
echo "Target Feed: $FEED"
echo "Target Sender: $SENDER"
echo ""

# Check if NATS CLI is available
if ! command -v nats &> /dev/null; then
    echo "❌ NATS CLI not found. Install it from: https://github.com/nats-io/natscli"
    echo "Then run: nats context add local --server $NATS_URL"
    exit 1
fi

echo "1️⃣  EXPLORE: Exchange Metadata"
echo "================================"
echo "Run these commands in separate terminals:"
echo ""
echo "# List all available contracts:"
echo "  nats kv ls EX_META"
echo ""
echo "# Get details of the AAH6 contract:"
echo "  nats kv get EX_META AAH6"
echo ""
echo "# Get details of other months (AAM6, AAU6):"
echo "  nats kv get EX_META AAM6"
echo "  nats kv get EX_META AAU6"
echo ""
echo "---"
echo "Questions to answer:"
echo "  Q1: What is the tick size for AAH6?"
echo "  Q2: What are the min/max volumes allowed?"
echo "  Q3: What is the position limit?"
echo "  Q4: What is max_tps (transactions per second)?"
echo ""

echo "2️⃣  EXPLORE: Market Data Feed"
echo "================================"
echo "Watch market data as it arrives:"
echo ""
echo "# Subscribe to BBO (best bid/offer) for AAH6:"
echo "  nats sub 'ex.bbo.AAH6'"
echo ""
echo "# Subscribe to market data (all events for AAH6):"
echo "  nats sub 'ex.md.AAH6.*'"
echo ""
echo "---"
echo "Questions to answer:"
echo "  Q5: What message types do you see? (A = add, E = execution, T = trade, C = cancel)"
echo "  Q6: How often does BBO update?"
echo "  Q7: Do market data messages have timestamps? (format?)"
echo "  Q8: What's the format of execution (E) messages? Fields?"
echo ""

echo "3️⃣  EXPLORE: Order Entry Protocol"
echo "===================================="
echo "Place an order and watch what happens:"
echo ""
echo "# Terminal 1: Subscribe to market data"
echo "  nats sub 'ex.md.AAH6.*'"
echo ""
echo "# Terminal 2: Place a single buy limit order at specific price"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 A AAH6 ORDER001 B 5 600 L'"
echo ""
echo "---"
echo "Questions to answer:"
echo "  Q9: What does the exchange reply with? (Accept/reject format?)"
echo "  Q10: Do you see 'A' (add to book) message on market data feed?"
echo "  Q11: If order is large, does it fill immediately? Partial or full?"
echo "  Q12: Do rejected orders generate any market data event?"
echo ""

echo "4️⃣  EXPLORE: Fill-and-Kill (F) Orders"
echo "======================================="
echo "Test F (fill-and-kill) order semantics:"
echo ""
echo "# Terminal 1: Subscribe to market data"
echo "  nats sub 'ex.md.AAH6.*'"
echo ""
echo "# Terminal 2: Place an aggressive F order (market order)"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 A AAH6 ORDER002 B 10 700 F'"
echo ""
echo "---"
echo "Questions to answer:"
echo "  Q13: Does F order execute fully or can it be rejected with partial fill?"
echo "  Q14: Do you see E (execution) messages for the F order?"
echo "  Q15: If not enough liquidity, does it reject or partially fill?"
echo ""

echo "5️⃣  EXPLORE: Order Cancellation"
echo "================================="
echo "Test cancel semantics:"
echo ""
echo "# Terminal 1: Post limit orders"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 A AAH6 ORDER003 B 5 595 L'"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 A AAH6 ORDER004 B 5 590 L'"
echo ""
echo "# Terminal 2: Subscribe to market data"
echo "  nats sub 'ex.md.AAH6.*'"
echo ""
echo "# Terminal 3: Cancel individual order"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 C AAH6 ORDER003'"
echo ""
echo "---"
echo "Questions to answer:"
echo "  Q16: What does exchange reply to cancel request?"
echo "  Q17: Do you see 'C' (cancel) message on market data feed?"
echo "  Q18: Does cancel confirm order didn't get filled before cancel?"
echo ""

echo "6️⃣  EXPLORE: Cancel Many (X Command)"
echo "======================================"
echo "Test bulk cancellation:"
echo ""
echo "# Post multiple orders:"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 A AAH6 ORDER005 B 5 585 L'"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 A AAH6 ORDER006 B 3 580 L'"
echo ""
echo "# Cancel all buy orders:"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 X AAH6 B 0'"
echo ""
echo "---"
echo "Questions to answer:"
echo "  Q19: Does X command respect feed/side/price selectors?"
echo "  Q20: How many orders does it report as cancelled?"
echo ""

echo "7️⃣  EXPLORE: Self-Trade Prevention (Q/W)"
echo "========================================="
echo "Test STP semantics:"
echo ""
echo "# Enable STP:"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 Q AAH6'"
echo ""
echo "# Place conflicting orders (post buy, then aggress from same sender):"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 A AAH6 ORDER007 B 5 600 L'"
echo "  nats req 'ex.req.TEST0001' 'TEST0001 A AAH6 ORDER008 S 3 600 F'"
echo ""
echo "---"
echo "Questions to answer:"
echo "  Q21: With STP enabled, do the orders match against each other?"
echo "  Q22: Or does the aggressive order just take from the book?"
echo "  Q23: What happens if we disable STP (W command)?"
echo ""

echo "8️⃣  EXPLORE: Rate Limits"
echo "========================"
echo "Test max_tps enforcement:"
echo ""
echo "# Get the contract's max_tps from EX_META:"
echo "  nats kv get EX_META AAH6"
echo ""
echo "# Spam orders at high rate:"
echo "  for i in {1..50}; do"
echo "    nats req 'ex.req.TEST0001' \"TEST0001 A AAH6 ORDER\$(printf '%03d' \$i) B 1 600 L\" &"
echo "  done"
echo "  wait"
echo ""
echo "---"
echo "Questions to answer:"
echo "  Q24: Do orders get rejected after hitting max_tps?"
echo "  Q25: What error code? (check PROTOCOL.md for reject codes)"
echo "  Q26: Is the connection dropped or just rejects?"
echo ""

echo ""
echo "=========================================="
echo "How to Document Your Findings"
echo "=========================================="
echo ""
echo "Create a file: candidate/PHASE2_FINDINGS.md"
echo ""
echo "Format:"
echo "# Phase 2 Findings"
echo ""
echo "## Contract Metadata (EX_META)"
echo "- Tick size: [answer to Q1]"
echo "- Min volume: [answer]"
echo "- Max volume: [answer]"
echo "- Position limit: [answer]"
echo "- Max TPS: [answer to Q4]"
echo ""
echo "## Message Types & Format"
echo "- A (Add): [describe format]"
echo "- E (Execution): [describe format]"
echo "- T (Trade): [describe format]"
echo "- C (Cancel): [describe format]"
echo ""
echo "## Order Entry Behavior"
echo "- Limit order execution: [describe]"
echo "- F order behavior: [describe]"
echo "- Cancel behavior: [describe]"
echo ""
echo "## Rate Limits & Edge Cases"
echo "- Max TPS enforcement: [describe]"
echo "- Error handling: [describe]"
echo ""
echo "## Assumptions Validated"
echo "- [List assumptions we verified]"
echo ""
echo "## Open Questions"
echo "- [List anything still unclear]"
echo ""

echo "=========================================="
echo "Next Steps"
echo "=========================================="
echo ""
echo "1. Run the commands above and observe the exchange behavior"
echo "2. Answer all 26 questions in PHASE2_FINDINGS.md"
echo "3. Update NOTES.md with Phase 2 progress"
echo "4. Use these findings to design the Quoter strategy"
echo ""
echo "Good luck! 🚀"
